# Generated by Django 5.1.3 on 2025-01-04 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_signout_child_child_room_delete_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.child')),
            ],
        ),
    ]
